#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# 腾讯云 COS：更新包的国内线路（#255，spec #248）。
# 建上海地域、公有读的存储桶，设流量告警和每月费用预算，建只能往这个桶上传的子账号，
# 把它的密钥存进公开仓库 zhengjiaqiao/sophia 的 Actions（release.yml 只在那里构建，#263 用）。
# 以后换账号、轮换泄露的密钥都重跑这一份：scripts/setup-cos.sh
# 本机只记非密钥的值（APPID、桶名）以便重跑时沿用；密钥只进 GitHub，不落盘。

export GH_REPO=zhengjiaqiao/sophia
ENV_FILE="$HOME/.config/sophia/cos-wizard.env"
mkdir -p "$(dirname "$ENV_FILE")"
COS_REGION=ap-shanghai

TOTAL_STAGES=8

banner "腾讯云 COS：建更新包的国内线路"

# ──────────────────────────────────────────────────────────────────────────
stage "登录腾讯云，记下 APPID"
open_url "https://console.cloud.tencent.com/developer"
step "用你的主账号登录。没做实名认证的先按页面提示做完（COS 要求实名）。"
step "在「账号信息」里找到 APPID：一串数字，注意不是「账号 ID」。"
while :; do
  ask COS_APPID "粘贴 APPID："
  [[ "$COS_APPID" =~ ^[0-9]{6,}$ ]] && break
  warn "APPID 是一串纯数字，再看一眼。"
done
write_env COS_APPID "$COS_APPID"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "建存储桶（上海、公有读）"
open_url "https://console.cloud.tencent.com/cos/bucket"
step "第一次进来会提示开通对象存储，先点开通。"
step "点「创建存储桶」："
note "    名称：sophia-releases（系统会自动在后面接上 -${COS_APPID}）"
note "    所属地域：中国大陆 → 上海（ap-shanghai）。地域建好后改不了。"
note "    数据冗余策略：单 AZ 存储（多 AZ 开了关不掉、存储费更贵；包都能从流水线重传）。"
note "    访问权限：「公有读私有写」。页面会提示有风险，确认即可：桶里只放公开的安装包和更新清单。"
step "其余（内容安全、版本控制、加密、压缩、日志）都保持默认关着，一路下一步到「创建」。"
pause "建好了按 Enter"
while :; do
  ask COS_BUCKET_NAME "桶名（不带 -APPID 的部分，直接 Enter 用 sophia-releases）："
  COS_BUCKET_NAME="${COS_BUCKET_NAME:-sophia-releases}"
  COS_BUCKET_NAME="${COS_BUCKET_NAME%-"$COS_APPID"}"
  COS_BUCKET="$COS_BUCKET_NAME-$COS_APPID"
  # 桶不存在时默认域名回 NoSuchBucket；存在时不管公有读能不能列目录，都不会是它
  body=$(curl -sS --max-time 15 "https://$COS_BUCKET.cos.$COS_REGION.myqcloud.com/" 2>&1 || true)
  if [[ "$body" == *NoSuchBucket* ]]; then
    warn "没找到桶 ${COS_BUCKET}（上海地域）。检查名字和地域。"
  elif [[ -z "$body" || "$body" == curl:* ]]; then
    warn "访问默认域名失败：${body:-无响应}"
    confirm "先跳过这个检查继续？" && break
  else
    printf '  %s✓ 找到桶%s %s\n' "$GREEN" "$RESET" "$COS_BUCKET"
    break
  fi
done
write_env COS_BUCKET_NAME "$COS_BUCKET_NAME"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "流量告警"
say "COS 不支持流量超了自动停，只能告警，所以这一步要设。"
note "下面的菜单名按腾讯云文档整理，控制台改过版的话以页面为准。"
open_url "https://console.cloud.tencent.com/monitor/alarm/policy"
step "点「新建策略」，监控类型选「云产品监控」，策略类型找「对象存储」。"
step "告警对象选桶 ${COS_BUCKET}。"
step "指标选「外网下行流量」，统计周期选能选的最长一档。"
note "    阈值建议：一天超过 10 GB 就告警（外网下行约 0.5 元/GB，以官网价格为准）。"
step "通知模板选一个会发到你手机和邮箱的（没有就新建），保存。"
pause "设好了按 Enter"

# ──────────────────────────────────────────────────────────────────────────
stage "每月费用预算（兜底）"
say "上一步按天看流量；这一步按月看花了多少钱，两头都有提醒。"
if confirm "要设每月费用预算吗？（推荐）"; then
  open_url "https://console.cloud.tencent.com/expense/overview"
  step "左侧「成本管理 → 预算管理」，点「新建预算」，选「月度费用预算」。"
  note "    金额建议 100 元；告警阈值 80% 和 100% 各一条，通知发到你手机和邮箱。"
  pause "设好了按 Enter"
else
  SKIPPED+=("每月费用预算（费用中心 → 成本管理 → 预算管理）")
fi

# ──────────────────────────────────────────────────────────────────────────
stage "建「只能往这个桶上传」的权限策略"
POLICY_NAME="sophia-cos-releases-write"
RES="qcs::cos:$COS_REGION:uid/$COS_APPID:$COS_BUCKET"
# 只给上传（含分片上传）与查看，不给删除：密钥泄露时最多往这个桶里多放文件
POLICY=$(cat <<JSON
{
  "version": "2.0",
  "statement": [
    {
      "effect": "allow",
      "action": [
        "name/cos:HeadObject",
        "name/cos:PutObject",
        "name/cos:InitiateMultipartUpload",
        "name/cos:UploadPart",
        "name/cos:CompleteMultipartUpload",
        "name/cos:AbortMultipartUpload",
        "name/cos:ListMultipartUploads",
        "name/cos:ListParts"
      ],
      "resource": ["$RES/*"]
    },
    {
      "effect": "allow",
      "action": ["name/cos:HeadBucket", "name/cos:GetBucket"],
      "resource": ["$RES/", "$RES/*"]
    }
  ]
}
JSON
)
if command -v pbcopy >/dev/null 2>&1; then
  printf '%s' "$POLICY" | pbcopy
  printf '  %s✓ 策略内容已复制到剪贴板%s\n' "$GREEN" "$RESET"
fi
open_url "https://console.cloud.tencent.com/cam/policy"
step "点「新建自定义策略」→「按策略语法创建」→ 模板选「空白模板」→ 下一步。"
step "策略名称填 ${POLICY_NAME}。"
step "把策略内容整段换成剪贴板里的（也就是下面这段），点完成。"
printf '%s%s%s\n' "$DIM" "$POLICY" "$RESET"
pause "建好了按 Enter"

# ──────────────────────────────────────────────────────────────────────────
stage "建子账号，拿到密钥"
open_url "https://console.cloud.tencent.com/cam"
step "用户列表里点「新建用户」→「自定义创建」→「可访问资源并接收消息」。"
step "用户名 sophia-release-ci；访问方式只勾「编程访问」，不勾控制台访问。"
step "设置权限时搜 ${POLICY_NAME}，只勾这一个，其余默认，完成。"
step "最后一页会显示 SecretId 和 SecretKey。SecretKey 只显示这一次，现在就复制到下面。"
while :; do
  ask_secret COS_SECRET_ID "粘贴 SecretId（输入不显示）："
  [[ "$COS_SECRET_ID" == AKID* ]] && break
  warn "SecretId 以 AKID 开头，再复制一次。"
done
while :; do
  ask_secret COS_SECRET_KEY "粘贴 SecretKey（输入不显示）："
  [[ -n "$COS_SECRET_KEY" ]] && break
  warn "SecretKey 是空的，再复制一次。"
done

# ──────────────────────────────────────────────────────────────────────────
stage "存进 GitHub"
say "发版流水线在公开仓库 $GH_REPO 里跑，所以密钥和桶名存在那里。"
note "  密钥：COS_SECRET_ID、COS_SECRET_KEY；变量：COS_BUCKET=${COS_BUCKET}、COS_REGION=$COS_REGION"
if confirm "写入 $GH_REPO 的 Actions？同名的旧值会被覆盖"; then
  set_secret COS_SECRET_ID "$COS_SECRET_ID"
  set_secret COS_SECRET_KEY "$COS_SECRET_KEY"
  set_var COS_BUCKET "$COS_BUCKET"
  set_var COS_REGION "$COS_REGION"
else
  SKIPPED+=("GitHub：gh secret set COS_SECRET_ID / COS_SECRET_KEY，gh variable set COS_BUCKET / COS_REGION（-R ${GH_REPO}）")
fi
unset COS_SECRET_ID COS_SECRET_KEY
pause

# ──────────────────────────────────────────────────────────────────────────
stage "核对：默认域名能公开下载"
PING_DIR=$(mktemp -d)
printf 'ok\n' > "$PING_DIR/ping.txt"
open -R "$PING_DIR/ping.txt" >/dev/null 2>&1 || note "测试文件在 $PING_DIR/ping.txt"
open_url "https://console.cloud.tencent.com/cos/bucket"
step "进桶 ${COS_BUCKET}，点「上传文件」，把刚在访达里选中的 ping.txt 传到根目录。"
PING_URL="https://$COS_BUCKET.cos.$COS_REGION.myqcloud.com/ping.txt"
while :; do
  pause "传好了按 Enter，我去下载一次"
  code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 "$PING_URL" 2>/dev/null || true)
  if [[ "$code" == 200 ]]; then
    printf '  %s✓ 能下载%s %s\n' "$GREEN" "$RESET" "$PING_URL"
    note "ping.txt 可以在控制台删掉，留着也没影响。"
    break
  fi
  warn "下载 $PING_URL 得到 ${code:-无响应}。403 多半是访问权限没选「公有读私有写」：桶的「权限管理」里能改。"
  if ! confirm "再试一次？"; then
    SKIPPED+=("核对公开下载：$PING_URL 应该返回 200")
    break
  fi
done
pause

finish
note "下一步：#263 发版流水线用 COS_SECRET_ID、COS_SECRET_KEY、COS_BUCKET、COS_REGION 往这个桶传包。"
