[package]
name = "symsync-core"
version = "0.2.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
tempfile = "3"
toml_edit = "0.25"
dirs = "7"
pathdiff = "0.2"
rusqlite = { version = "0.40.2", features = ["bundled", "backup"] }

[target.'cfg(windows)'.dependencies]
junction = "2"
