#!/usr/bin/env bash
#
# 向导：建一个只能写 zhengjiaqiao/homebrew-tap 的 fine-grained 令牌，存成公开仓库 zhengjiaqiao/sophia 的
# secret HOMEBREW_TAP_TOKEN。发版工作流（.github/workflows/homebrew-cask.yml）用它把 cask 推到 tap。
# 第一次配、令牌过期或被撤销之后各跑一次：
#   packaging/setup-tap-token.sh
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
# shellcheck disable=SC2034  # 向导库里的 RED 这个向导没用到

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# 令牌只在内存里过一遍：不写 .env（读也不读，免得把别处的同名值当默认值），
# 用 read -s 读入、经标准输入交给 gh，不进命令行参数、不进 shell 历史、不打印。
ENV_FILE=/dev/null

PUBLIC_REPO=zhengjiaqiao/sophia
TAP_REPO=zhengjiaqiao/homebrew-tap
SECRET_NAME=HOMEBREW_TAP_TOKEN
EXPIRES_DAYS=366
TOKEN_URL="https://github.com/settings/personal-access-tokens/new?name=sophia+homebrew-tap&description=Sophia+release+workflow+pushes+Casks%2Fsophia.rb+to+${TAP_REPO/\//%2F}&target_name=${TAP_REPO%%/*}&expires_in=${EXPIRES_DAYS}&contents=write"

# probe_push TOKEN：和 git push 开头那一下同一个请求。200 能推，401 认不出，403/404 没授权这个仓库
probe_push() {
  printf 'user = "x-access-token:%s"\n' "$1" |
    curl -sS -o /dev/null -w '%{http_code}' -K - \
      "https://github.com/${TAP_REPO}.git/info/refs?service=git-receive-pack" || true
}

TOTAL_STAGES=4

banner "Sophia：给发版工作流配推 Homebrew tap 的令牌（${SECRET_NAME}）"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "检查 gh"
say "令牌最后要用 gh 写进公开仓库 ${PUBLIC_REPO} 的 secret，先确认 gh 能用。"
if ! command -v gh >/dev/null 2>&1; then
  warn "没找到 gh。先 brew install gh，再 gh auth login，然后重跑这个向导。"
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  warn "gh 还没登录。先 gh auth login，然后重跑这个向导。"
  exit 1
fi
if ! existing=$(gh secret list --repo "$PUBLIC_REPO" 2>&1); then
  warn "读不了 ${PUBLIC_REPO} 的 secret 列表（要仓库管理员权限）："
  note "$existing"
  exit 1
fi
if grep -q "^${SECRET_NAME}[[:space:]]" <<<"$existing"; then
  note "${SECRET_NAME} 已经有了（多半是要换掉过期的那个），这次会覆盖它："
  note "$(grep "^${SECRET_NAME}[[:space:]]" <<<"$existing")"
else
  note "${PUBLIC_REPO} 还没有 ${SECRET_NAME}，这次新建。"
fi
pause "按回车继续"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "在 GitHub 上建 fine-grained 令牌"
say "浏览器会打开令牌创建页，名字、说明、所有者、有效期、Contents 权限已经预填好。逐项核对："
open_url "$TOKEN_URL"
step "Token name：sophia homebrew-tap（同名的已存在就在后面加个日期）"
step "Resource owner：${TAP_REPO%%/*}"
step "Expiration：${EXPIRES_DAYS} days（到期日 $(date -v+"${EXPIRES_DAYS}"d +%F 2>/dev/null || date -d "+${EXPIRES_DAYS} days" +%F)）"
note "  也可以选 No expiration；令牌只能写 tap 仓库，泄露了也只影响它，但长期不换就只能靠自己记得撤销。"
step "Repository access：选 Only select repositories，下拉里只勾 ${TAP_REPO}"
step "Permissions → Repository permissions → Contents：Read and write（Metadata 会自动变成 Read-only，不用管）"
step "别的权限都不要加。拉到底点 Generate token，确认后复制 github_pat_ 开头的那一串"
warn "令牌只显示这一次。先别关页面，下一步粘贴。"
pause "复制好了按回车"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "粘贴令牌并核对能推 tap"
say "粘贴时屏幕上不显示。向导会用它试连一下 ${TAP_REPO}，看能不能推。"
TOKEN=""
while :; do
  ask_secret TOKEN "粘贴令牌（不显示）："
  TOKEN="${TOKEN//[[:space:]]/}"
  if [[ -z "$TOKEN" ]]; then
    warn "没读到内容，再粘一次。"
    continue
  fi
  code=$(probe_push "$TOKEN")
  case "$code" in
    200)
      printf '  %s✓ 能推 %s%s\n' "$GREEN" "$TAP_REPO" "$RESET"
      break ;;
    401)
      warn "GitHub 不认这个令牌（HTTP 401）：可能粘漏了一截，或者复制的不是刚生成的那个。" ;;
    000)
      warn "连不上 github.com，检查网络后再粘一次。" ;;
    *)
      warn "令牌有效，但推不了 ${TAP_REPO}（HTTP ${code}）：回到令牌页，Repository access 要勾上它，Contents 要 Read and write。"
      note "  改完权限不用重新生成，同一个令牌再粘一次即可。" ;;
  esac
  confirm "再试一次？" || { warn "没写 secret，退出。"; exit 1; }
done
pause "按回车继续"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "写进 ${PUBLIC_REPO} 的 secret"
say "要执行：gh secret set ${SECRET_NAME} --repo ${PUBLIC_REPO}（令牌从标准输入传，不出现在命令行里）"
if ! confirm "写入？"; then
  unset TOKEN
  warn "没写 secret，退出。"
  exit 1
fi
if ! printf '%s' "$TOKEN" | gh secret set "$SECRET_NAME" --repo "$PUBLIC_REPO"; then
  unset TOKEN
  warn "gh secret set 失败，见上面的报错。修好后重跑这个向导。"
  exit 1
fi
unset TOKEN
WRITTEN_SECRET+=("$SECRET_NAME → $PUBLIC_REPO")
say "gh secret list --repo ${PUBLIC_REPO}："
if ! gh secret list --repo "$PUBLIC_REPO" | grep "^${SECRET_NAME}[[:space:]]"; then
  warn "列表里没看到 ${SECRET_NAME}，到 https://github.com/${PUBLIC_REPO}/settings/secrets/actions 看一眼。"
  exit 1
fi
pause "按回车看收尾"

finish
note "令牌到期前 GitHub 会发邮件提醒；到期后发版的「Homebrew cask」那一步会红，报 HTTP 401。"
note "那时重跑这个向导换一个新令牌，再手动运行一次补推（tag 填最近发布的版本）："
note "  gh workflow run homebrew-cask.yml -R ${PUBLIC_REPO} -f tag=<最近发布的 tag>"
printf '\n'
